[project]
name = "dhamma-studio"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "bottle==0.13.4",
    "mutagen==1.48.1",
    "numpy==2.5.2",
    "packaging==26.3",
    "pandas==3.0.5",
    "pillow==12.3.0",
    "proxy-tools==0.1.0",
    "pygame==2.6.1",
    "pyqt6==6.11.0",
    "pyqt6-qt6==6.11.2",
    "pyqt6-sip==13.12.0",
    "pyqt6-webengine==6.11.0",
    "pyqt6-webengine-qt6==6.11.2",
    "python-dateutil==2.9.0.post0",
    "pywebview==6.2.1",
    "qtpy==2.4.3",
    "scikit-learn==1.9.0",
    "sentence-transformers==6.0.1",
    "six==1.17.0",
    "torch==2.13.0",
    "typing-extensions==4.16.0",
]

[dependency-groups]
build = [
    "pyinstaller>=6.22.2",
]
